// Mongo document shapes for the inventory feature. Kept separate from
// `domain::inventory` (the API-facing types) so BSON concerns like
// `ObjectId` never leak into request/response payloads.

use mongodb::bson::{DateTime as BsonDateTime, oid::ObjectId};
use serde::{Deserialize, Serialize};

use crate::{
    core::{constants::prefixes, id::generate_id},
    domain::inventory::{
        BarcodeSource, CategoryInfo, Product, StockMovement, StockMovementType, SubcategoryInfo,
    },
};

/// Mongo document shape representing an inventory product.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductDocument {
    /// MongoDB internal document identifier.
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub id: Option<ObjectId>,
    /// Unique business key identifying this product (e.g. prd_...).
    #[serde(default)]
    pub key: String,
    /// Human-readable SKU code (e.g. PHO-SCR-0001).
    pub sku: String,
    /// Barcode string for scanning (e.g. EAN-13), if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub barcode: Option<String>,
    /// How the barcode was assigned (generated by system or manual).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub barcode_source: Option<BarcodeSource>,
    /// Product name or title.
    pub name: String,
    /// Foreign key referencing the parent category.
    pub category_key: String,
    /// Foreign key referencing the subcategory.
    pub subcategory_key: String,
    /// Cost/wholesale price in cents.
    pub cost_price_cents: i64,
    /// Retail selling price in cents.
    pub selling_price_cents: i64,
    /// Current number of units in inventory stock.
    pub stock_quantity: i64,
    /// Minimum threshold count for low-stock warning alerts.
    pub min_stock_threshold: i64,
    /// Version counter for optimistic locking.
    #[serde(default = "default_version")]
    pub version: i64,
    /// Timestamp when product was created.
    #[serde(default = "BsonDateTime::now")]
    pub created_at: BsonDateTime,
    /// Timestamp when product was last updated.
    pub updated_at: BsonDateTime,
    /// Timestamp when product was soft-deleted, if applicable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<BsonDateTime>,
    /// Device identifier that last updated this product.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by_device: Option<String>,
}

fn default_version() -> i64 {
    1
}

impl ProductDocument {
    /// `category_name`/`subcategory_name` are resolved by the service layer
    /// (a lookup by `category_key`/`subcategory_key`) before calling this —
    /// this conversion stays a pure/sync mapping with no DB access, matching
    /// every other `into_*` conversion in this file.
    pub fn into_product(self, category_name: String, subcategory_name: String) -> Product {
        let key = if self.key.is_empty() {
            generate_id(prefixes::PRODUCT)
        } else {
            self.key
        };
        Product {
            id: self
                .id
                .expect("persisted product document must have an id")
                .to_hex(),
            key,
            sku: self.sku,
            barcode: self.barcode,
            barcode_source: self.barcode_source,
            name: self.name,
            category_key: self.category_key,
            category: category_name,
            subcategory_key: self.subcategory_key,
            subcategory: subcategory_name,
            cost_price_cents: self.cost_price_cents,
            selling_price_cents: self.selling_price_cents,
            stock_quantity: self.stock_quantity,
            min_stock_threshold: self.min_stock_threshold,
            created_at: self.created_at.to_chrono(),
            updated_at: self.updated_at.to_chrono(),
            version: self.version,
            deleted_at: self.deleted_at.map(|d| d.to_chrono()),
            updated_by_device: self.updated_by_device,
        }
    }
}

/// Mongo document shape representing a stock movement audit log entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StockMovementDocument {
    /// MongoDB internal document identifier.
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub id: Option<ObjectId>,
    /// Unique business key identifying this stock movement record (e.g. stm_...).
    #[serde(default)]
    pub key: String,
    /// MongoDB ObjectId of the affected product.
    pub product_id: ObjectId,
    /// Quantity change (positive for additions, negative for reductions).
    pub quantity_delta: i64,
    /// Reason or classification for this movement (e.g. sale, intake, manual adjustment).
    pub movement_type: StockMovementType,
    /// External reference key (e.g. invoice key, purchase key, repair ticket key).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<String>,
    /// Optional explanatory note or comment.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// Concurrency version counter for optimistic locking.
    #[serde(default = "default_version")]
    pub version: i64,
    /// Timestamp when this stock movement occurred.
    pub created_at: BsonDateTime,
    /// Timestamp when this movement record was last modified.
    #[serde(default = "BsonDateTime::now")]
    pub updated_at: BsonDateTime,
    /// Soft-delete timestamp, if deleted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<BsonDateTime>,
    /// Device identifier of the client creating/updating this movement.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by_device: Option<String>,
}

impl StockMovementDocument {
    pub fn into_stock_movement(self) -> StockMovement {
        let key = if self.key.is_empty() {
            generate_id(prefixes::STOCK_MOVEMENT)
        } else {
            self.key
        };
        StockMovement {
            id: self
                .id
                .expect("persisted stock movement document must have an id")
                .to_hex(),
            key,
            product_id: self.product_id.to_hex(),
            quantity_delta: self.quantity_delta,
            movement_type: self.movement_type,
            reference_id: self.reference_id,
            note: self.note,
            created_at: self.created_at.to_chrono(),
            updated_at: self.updated_at.to_chrono(),
            version: self.version,
            deleted_at: self.deleted_at.map(|d| d.to_chrono()),
            updated_by_device: self.updated_by_device,
        }
    }
}

/// A main category, persisted in the `categories` collection so the valid
/// set is a single DB-backed source of truth (for both API responses and
/// product validation) instead of a static table baked into the binary.
/// Its subcategories are NOT embedded here — they're independent documents
/// in the `subcategories` collection (see `SubcategoryDocument`), each
/// referencing this category by `key` so a category rename never needs to
/// cascade anywhere. Seeded via `cargo run --bin seed_providers`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CategoryDocument {
    /// MongoDB internal document identifier.
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub id: Option<ObjectId>,
    /// Unique business key identifying this category (e.g. cat_...).
    #[serde(default)]
    pub key: String,
    /// Category display name.
    pub name: String,
    /// Icon identifier or name for UI display.
    pub icon: String,
    /// Color hex code or theme token for UI badges.
    pub color: String,
    /// Concurrency version counter for optimistic locking.
    #[serde(default = "default_version")]
    pub version: i64,
    /// Timestamp when category was created.
    #[serde(default = "BsonDateTime::now")]
    pub created_at: BsonDateTime,
    /// Timestamp when category was last updated.
    #[serde(default = "BsonDateTime::now")]
    pub updated_at: BsonDateTime,
    /// Soft-delete timestamp, if deleted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<BsonDateTime>,
    /// Device identifier that last updated this category.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by_device: Option<String>,
}

impl CategoryDocument {
    /// `subcategories` is resolved by the service layer (a query against
    /// the `subcategories` collection filtered by this category's `key`)
    /// before calling this — see the comment on `ProductDocument::into_product`.
    pub fn into_category_info(self, subcategories: Vec<SubcategoryInfo>) -> CategoryInfo {
        let key = if self.key.is_empty() {
            generate_id(prefixes::CATEGORY)
        } else {
            self.key
        };
        CategoryInfo {
            key,
            name: self.name,
            icon: self.icon,
            color: self.color,
            subcategories,
            created_at: self.created_at.to_chrono(),
            updated_at: self.updated_at.to_chrono(),
            version: self.version,
            deleted_at: self.deleted_at.map(|d| d.to_chrono()),
            updated_by_device: self.updated_by_device,
        }
    }
}

/// A subcategory, persisted in its own `subcategories` collection rather
/// than embedded on `CategoryDocument` — this gives every subcategory its
/// own stable `key` (so products can reference it directly, and duplicate
/// names are only disallowed within the same category, not globally) and
/// lets a category be renamed without touching any subcategory or product
/// document. `category_key` is the FK back to `CategoryDocument.key`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubcategoryDocument {
    /// MongoDB internal document identifier.
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub id: Option<ObjectId>,
    /// Unique business key identifying this subcategory (e.g. sub_...).
    #[serde(default)]
    pub key: String,
    /// Foreign key referencing the parent category key.
    pub category_key: String,
    /// Subcategory display name.
    pub name: String,
    /// Concurrency version counter for optimistic locking.
    #[serde(default = "default_version")]
    pub version: i64,
    /// Timestamp when subcategory was created.
    #[serde(default = "BsonDateTime::now")]
    pub created_at: BsonDateTime,
    /// Timestamp when subcategory was last updated.
    #[serde(default = "BsonDateTime::now")]
    pub updated_at: BsonDateTime,
    /// Soft-delete timestamp, if deleted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<BsonDateTime>,
    /// Device identifier that last updated this subcategory.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by_device: Option<String>,
}

impl SubcategoryDocument {
    pub fn into_subcategory_info(self) -> SubcategoryInfo {
        let key = if self.key.is_empty() {
            generate_id(prefixes::SUBCATEGORY)
        } else {
            self.key
        };
        SubcategoryInfo {
            key,
            category_key: self.category_key,
            name: self.name,
            created_at: self.created_at.to_chrono(),
            updated_at: self.updated_at.to_chrono(),
            version: self.version,
            deleted_at: self.deleted_at.map(|d| d.to_chrono()),
            updated_by_device: self.updated_by_device,
        }
    }
}
