//! Standardized status and error code strings used in API response envelopes across all modules.

// System & Auth Status Codes
pub const NOT_FOUND: &str = "NOT_FOUND";
pub const VALIDATION_ERROR: &str = "VALIDATION_ERROR";
pub const UNAUTHORIZED: &str = "UNAUTHORIZED";
pub const FORBIDDEN: &str = "FORBIDDEN";
pub const ADMIN_REQUIRED: &str = "ADMIN_REQUIRED";
pub const INTERNAL_SERVER_ERROR: &str = "INTERNAL_SERVER_ERROR";

// Products Status Codes
pub const PRODUCT_NOT_FOUND: &str = "PRODUCT_NOT_FOUND";
pub const SKU_ALREADY_EXISTS: &str = "SKU_ALREADY_EXISTS";
pub const BARCODE_ALREADY_EXISTS: &str = "BARCODE_ALREADY_EXISTS";
pub const INSUFFICIENT_STOCK: &str = "INSUFFICIENT_STOCK";

// Categories & Subcategories Status Codes
pub const CATEGORY_NOT_FOUND: &str = "CATEGORY_NOT_FOUND";
pub const CATEGORY_ALREADY_EXISTS: &str = "CATEGORY_ALREADY_EXISTS";
pub const CATEGORY_HAS_PRODUCTS: &str = "CATEGORY_HAS_PRODUCTS";
pub const CATEGORY_IN_USE: &str = "CATEGORY_IN_USE";
pub const SUBCATEGORY_NOT_FOUND: &str = "SUBCATEGORY_NOT_FOUND";
pub const SUBCATEGORY_ALREADY_EXISTS: &str = "SUBCATEGORY_ALREADY_EXISTS";
pub const SUBCATEGORY_HAS_PRODUCTS: &str = "SUBCATEGORY_HAS_PRODUCTS";
pub const SUBCATEGORY_IN_USE: &str = "SUBCATEGORY_IN_USE";
pub const INVALID_ICON: &str = "INVALID_ICON";
pub const INVALID_COLOR: &str = "INVALID_COLOR";

// Suppliers Status Codes
pub const SUPPLIER_NOT_FOUND: &str = "SUPPLIER_NOT_FOUND";
pub const SUPPLIER_HAS_PURCHASES: &str = "SUPPLIER_HAS_PURCHASES";
pub const SUPPLIER_PRODUCT_LINK_NOT_FOUND: &str = "SUPPLIER_PRODUCT_LINK_NOT_FOUND";

// Customers Status Codes
pub const CUSTOMER_NOT_FOUND: &str = "CUSTOMER_NOT_FOUND";
pub const CUSTOMER_HAS_OUTSTANDING_BALANCE: &str = "CUSTOMER_HAS_OUTSTANDING_BALANCE";

// Repairs & Print Jobs Status Codes
pub const REPAIR_NOT_FOUND: &str = "REPAIR_NOT_FOUND";
pub const PRINT_JOB_NOT_FOUND: &str = "PRINT_JOB_NOT_FOUND";
pub const INVALID_JOB_STATUS: &str = "INVALID_JOB_STATUS";
pub const INVALID_JOB_TYPE: &str = "INVALID_JOB_TYPE";
pub const REPAIR_PRICE_REQUIRED: &str = "REPAIR_PRICE_REQUIRED";

// Billing Status Codes
pub const INVOICE_NOT_FOUND: &str = "INVOICE_NOT_FOUND";
pub const INVOICE_ALREADY_CANCELLED: &str = "INVOICE_ALREADY_CANCELLED";
pub const INVOICE_HAS_PAYMENTS_CANNOT_CANCEL: &str = "INVOICE_HAS_PAYMENTS_CANNOT_CANCEL";
pub const PAYMENT_EXCEEDS_BALANCE: &str = "PAYMENT_EXCEEDS_BALANCE";
pub const RETURN_NOT_FOUND: &str = "RETURN_NOT_FOUND";
pub const RETURN_QUANTITY_EXCEEDED: &str = "RETURN_QUANTITY_EXCEEDED";
pub const INVOICE_NOT_RETURNABLE: &str = "INVOICE_NOT_RETURNABLE";
pub const INVALID_REFUND_AMOUNT: &str = "INVALID_REFUND_AMOUNT";

// Users & Auth Status Codes
pub const INVALID_CREDENTIALS: &str = "INVALID_CREDENTIALS";
pub const USER_NOT_FOUND: &str = "USER_NOT_FOUND";
pub const EMAIL_ALREADY_EXISTS: &str = "EMAIL_ALREADY_EXISTS";
pub const USER_INACTIVE: &str = "USER_INACTIVE";
pub const PERMISSION_DENIED: &str = "PERMISSION_DENIED";
pub const ADMIN_ALREADY_EXISTS: &str = "ADMIN_ALREADY_EXISTS";

// Sync, Concurrency & Idempotency Status Codes
pub const VERSION_CONFLICT: &str = "VERSION_CONFLICT";
pub const REFERENCE_NOT_FOUND: &str = "REFERENCE_NOT_FOUND";
pub const CURSOR_INVALID: &str = "CURSOR_INVALID";
pub const IDEMPOTENCY_KEY_REUSED: &str = "IDEMPOTENCY_KEY_REUSED";
pub const IDEMPOTENCY_IN_PROGRESS: &str = "IDEMPOTENCY_IN_PROGRESS";
pub const SEQUENCE_NOT_FOUND: &str = "SEQUENCE_NOT_FOUND";
pub const SEQUENCE_EXPIRED: &str = "SEQUENCE_EXPIRED";
pub const SEQUENCE_BLOCK_DEPLETED: &str = "SEQUENCE_BLOCK_DEPLETED";
